import React from "react";
import styled from "@emotion/styled";
/**
 * `<BubbleChart>` ('Bubble chart')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <BubbleChart/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/86b67cf5-b711-4961-8bd2-502b8fd0ddce)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/1567:3653 -->
 */
export function BubbleChart() {
  return (
    <RootWrapperBubbleChart>
      <Background />
      <BigWidgetBubbleChart>
        <BgLines />
        <BgLines_0001 />
        <BubbleChart_0001>
          <Bubble />
          <Bubble_0001 />
          <Bubble_0002 />
          <Bubble_0003 />
          <Bubble_0004 />
          <Bubble_0005 />
          <Bubble_0006 />
          <Bubble_0007 />
          <Bubble_0008 />
          <Bubble_0009 />
          <Bubble_0010 />
          <Bubble_0011 />
          <Bubble_0012 />
          <Bubble_0013 />
          <Bubble_0014 />
          <Bubble_0015 />
          <Bubble_0016 />
          <Bubble_0017 />
        </BubbleChart_0001>
        <Investments>
          <Time>3 month</Time>
          <Tittle>Investments</Tittle>
          <Value>$76,644</Value>
        </Investments>
        <Design>
          <Time_0001>3 month</Time_0001>
          <Value_0001>$32,982</Value_0001>
          <Title>Design</Title>
        </Design>
        <Finance>
          <Value_0002>$23,657</Value_0002>
          <Title_0001>Finance</Title_0001>
        </Finance>
        <Business>
          <Value_0003>$21,987</Value_0003>
          <Title_0002>Business</Title_0002>
        </Business>
        <Development>
          <Value_0004>$31,657</Value_0004>
          <Title_0003>Development</Title_0003>
        </Development>
      </BigWidgetBubbleChart>
      <Title_0004>Design faster</Title_0004>
      <Bubble_0018 />
      <Bubble_0019 />
      <Bubble_0020 />
      <Bubble_0021 />
      <Bubble_0022 />
      <Timeline>Timeline</Timeline>
      <Timeline_0001>
        <BackgroundElement />
        <DateRangePicker>
          <TimePeriod>
            <Period>1W</Period>
          </TimePeriod>
          <TimePeriod>
            <Period>1M</Period>
          </TimePeriod>
          <TimePeriod>
            <Hover />
            <Period_0002>3M</Period_0002>
          </TimePeriod>
          <TimePeriod>
            <Period>1Y</Period>
          </TimePeriod>
          <TimePeriod>
            <Period>ALL</Period>
          </TimePeriod>
        </DateRangePicker>
      </Timeline_0001>
      <NavigationBar>
        <Background_0001 />
        <Search>
          <Input />
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/572196a3-0ca2-40cd-b7ec-e4eb4eb79d06"
            alt="icon"
          />
        </Search>
        <Tab />
        <Menu>
          <Label>Statistics</Label>
          <Label_0001>Overview</Label_0001>
          <Label>Dashboard</Label>
          <Label>Analytics</Label>
        </Menu>
        <Profile
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0bbf2f8e-a6ec-4834-af38-a5c73ff54056"
          alt="icon"
        />
        <Option
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/387e33c6-8185-4acb-9a27-c573debcbcad"
          alt="icon"
        />
        <Name>WASSERSTOFF</Name>
        <WstfLogo1>
          <Group>
            <Vector
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/01d4aeab-00d0-43c0-8772-3466079048ab"
              alt="icon"
            />
            <Vector
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1853c2e6-39f5-4be9-ba75-e926d6a8ab1a"
              alt="icon"
            />
          </Group>
        </WstfLogo1>
      </NavigationBar>
      <Footer>
        <Bg />
        <OrionDataVisualisation>Orion data visualisation</OrionDataVisualisation>
        <_2019>2022</_2019>
      </Footer>
      <InformerTrendGoods>
        <Value_0005>204</Value_0005>
        <Title_0005>Trend goods</Title_0005>
        <Icon_0001>
          <Stroke />
          <Favorite
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ab845864-de12-46e9-af01-1c560873b39d"
            alt="icon"
          />
        </Icon_0001>
      </InformerTrendGoods>
      <InformerTrendGoods_0001>
        <Value_0006>65,540</Value_0006>
        <Title_0006>Shopping views</Title_0006>
        <Icon_0001>
          <Stroke />
          <Eye
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f18b268a-0abd-4b2a-8266-ba7fc26d1be4"
            alt="icon"
          />
        </Icon_0001>
      </InformerTrendGoods_0001>
      <InformerTrendGoods_0002>
        <Value_0007>324</Value_0007>
        <Title_0007>Store dynamics</Title_0007>
        <Icon_0001>
          <Stroke />
          <Chart
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9436cd85-885b-4fa9-99f2-93273a55222f"
            alt="icon"
          />
        </Icon_0001>
      </InformerTrendGoods_0002>
      <PanelGroup>
        <Zoom>
          <Bg_0001 />
          <Plus
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c0947ebf-dc7a-470c-a766-45d035fb0f83"
            alt="icon"
          />
          <Minus
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5b208cbb-a2ba-4a02-bb20-61cb4d098150"
            alt="icon"
          />
        </Zoom>
        <Map>
          <Bg_0001 />
          <Map_0001
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f2beea30-bb5b-49d7-a17f-29e1f646d456"
            alt="icon"
          />
        </Map>
        <Tool>
          <Bg_0001 />
          <Node
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3c6c2aa5-3abd-4b90-8df1-c8c0417961c4"
            alt="icon"
          />
          <Element
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/836b0754-091c-4978-b9c1-e7d799d222c8"
            alt="icon"
          />
          <Path
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1bc705e8-4ec4-4eeb-8cf5-a77f5d8baf7f"
            alt="icon"
          />
        </Tool>
      </PanelGroup>
      <WidgetMSizeCombinedCircleChartWithDynamicTable>
        <Graph>
          <ChartDoubleBigCircleChart>
            <Chart_0001>
              <ChartBg
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/72f35aeb-9373-4447-84f0-3a40244bafbc"
                alt="image from ellipse"
              />
              <ChartBg_0001
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0dded0b8-1af1-4511-93b2-2b4e54ab4df3"
                alt="image from ellipse"
              />
              <Progress1
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/353821f8-5761-4cf7-bbff-b007add5025a"
                alt="image from ellipse"
              />
              <Progress2
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/23c6a3ff-53a9-4122-a790-208978b2cb32"
                alt="image from ellipse"
              />
              <Progress3
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2d677a1a-7b6a-4aee-ab2a-b41d7e0175ef"
                alt="image from ellipse"
              />
              <Bg_0004 />
            </Chart_0001>
            <Icon_0004
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6988c05c-cb3f-41fa-883a-30b6dcfb2c7b"
              alt="icon"
            />
          </ChartDoubleBigCircleChart>
          <Info>
            <Title_0008>
              <Name_0001>Total earning</Name_0001>
            </Title_0008>
            <Value_0008>
              <Amount>$12,875</Amount>
              <Indicator>
                <ArrowUp>
                  <Arrow xmlns="http://www.w3.org/2000/svg">
                    <path fill="rgb(0, 185, 41)" d="M6.00004 0L12 8L0 8L6.00004 0Z" />
                  </Arrow>
                </ArrowUp>
                <Percent>2%</Percent>
              </Indicator>
            </Value_0008>
            <Detail>Compared to $21,504 last year</Detail>
          </Info>
        </Graph>
        <Table>
          <Row>
            <Name_0002>Presentation</Name_0002>
            <Amount_0001>862</Amount_0001>
            <Graph_0001>
              <Column />
              <Column_0001 />
              <Column_0002 />
              <Column_0003 />
              <Chart_0002
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a51a663d-44c5-4237-92a4-4aed3928ce73"
                alt="image of Chart"
              />
            </Graph_0001>
          </Row>
          <Row>
            <Name_0002>Development</Name_0002>
            <Amount_0001>753</Amount_0001>
            <Graph_0001>
              <Column />
              <Column_0001 />
              <Column_0002 />
              <Column_0003 />
              <Chart_0002
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a412f7a3-26aa-4679-bc94-5927df0a7b44"
                alt="image of Chart"
              />
            </Graph_0001>
          </Row>
          <Row>
            <Name_0002>Research</Name_0002>
            <Amount_0001>553</Amount_0001>
            <Graph_0001>
              <Column />
              <Column_0001 />
              <Column_0002 />
              <Column_0003 />
              <Chart_0004
                src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/66d670f5-f3aa-4231-a07f-29ecb5452053"
                alt="image of Chart"
              />
            </Graph_0001>
          </Row>
        </Table>
      </WidgetMSizeCombinedCircleChartWithDynamicTable>
      <WidgetMSizeOmpositeIndex>
        <Informer>
          <Title_0009>
            <Name_0005>Total earning</Name_0005>
          </Title_0009>
          <Value_0008>
            <Amount_0004>$12,875</Amount_0004>
            <Indicator>
              <ArrowUp>
                <Arrow xmlns="http://www.w3.org/2000/svg">
                  <path fill="rgb(56, 242, 97)" d="M6.00004 0L12 8L0 8L6.00004 0Z" />
                </Arrow>
              </ArrowUp>
              <Percent_0001>10%</Percent_0001>
            </Indicator>
          </Value_0008>
          <Detail_0001>Compared to $21,490 last year</Detail_0001>
        </Informer>
        <Divider
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/00d5a0c4-5f07-4db2-aecf-a89047f0690f"
          alt="image of Divider"
        />
        <Informer>
          <Title_0009>
            <Name_0006>Sales</Name_0006>
          </Title_0009>
          <Value_0008>
            <Amount_0004>$43,123</Amount_0004>
            <Indicator>
              <ArrowUp>
                <Arrow xmlns="http://www.w3.org/2000/svg">
                  <path fill="rgb(56, 242, 97)" d="M6.00004 0L12 8L0 8L6.00004 0Z" />
                </Arrow>
              </ArrowUp>
              <Percent_0001>12%</Percent_0001>
            </Indicator>
          </Value_0008>
          <Detail_0001>Compared to $21,490 last year</Detail_0001>
        </Informer>
      </WidgetMSizeOmpositeIndex>
      <TableIndicatorTable>
        <Row_0003>
          <Summary>
            <Name_0007>Travel</Name_0007>
            <Amount_0006>760</Amount_0006>
            <Summary_0001>2,540</Summary_0001>
          </Summary>
          <Status>
            <ArrowUp>
              <Arrow xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(0, 185, 41)" d="M6.00004 0L12 8L0 8L6.00004 0Z" />
              </Arrow>
            </ArrowUp>
          </Status>
        </Row_0003>
        <Row_0003>
          <Summary>
            <Name_0007>Presentation</Name_0007>
            <Amount_0006>650</Amount_0006>
            <Summary_0001>2,304</Summary_0001>
          </Summary>
          <Status>
            <ArrowUp>
              <Arro xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(255, 45, 46)" d="M6.00004 0L12 8L0 8L6.00004 0Z" />
              </Arro>
            </ArrowUp>
          </Status>
        </Row_0003>
        <Row_0003>
          <Summary>
            <Name_0007>Business</Name_0007>
            <Amount_0006>612</Amount_0006>
            <Summary_0001>2,140</Summary_0001>
          </Summary>
          <Status>
            <ArrowUp>
              <Arrow xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(0, 185, 41)" d="M6.00004 0L12 8L0 8L6.00004 0Z" />
              </Arrow>
            </ArrowUp>
          </Status>
        </Row_0003>
      </TableIndicatorTable>
    </RootWrapperBubbleChart>
  );
}

const RootWrapperBubbleChart = styled.div`
	min-height: 150vh;
    width: 1947px;
	background-color: rgb(250, 250, 250);
	position: relative;
`;

const Background = styled.div`
	background-color: rgb(238, 241, 250);
	border-top-left-radius: 73px;
	border-bottom-left-radius: 73px;
	position: absolute;
	left: 400px;
	top: 60px;
	right: 0px;
	bottom: 38px;
`;

const BigWidgetBubbleChart = styled.div`
	width: 863px;
	height: 778px;
	position: absolute;
	left: calc((calc((50% + 148px)) - 432px));
	top: calc((calc((50% + -23px)) - 389px));
`;

const BgLines = styled.div`
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	background-color: white;
	border-radius: 648px / 648px;
	position: absolute;
	left: 119px;
	top: 65px;
	right: 96px;
	bottom: 65px;
`;

const BgLines_0001 = styled.div`
	border-radius: 778px / 778px;
	position: absolute;
	left: 54px;
	top: 0px;
	right: 31px;
	bottom: 0px;
`;

const BubbleChart_0001 = styled.div`
	width: 863px;
	height: 543px;
	position: absolute;
	left: 0px;
	top: 111px;
`;

const Bubble = styled.div`
	box-shadow: 0px 40px 80px  rgba(35, 0, 248, 0.24),0px 2px 10px  rgba(255, 255, 255, 0.58),0px -20px 50px  rgba(124, 161, 255, 0.37),10px 16px 20px  rgba(207, 163, 252, 0.95);
	background: radial-gradient(rgb(131, 143, 255), rgba(227, 230, 255, 0));
	border-radius: 250px / 250px;
	position: absolute;
	left: 323px;
	top: 161px;
	right: 290px;
	bottom: 132px;
`;

const Bubble_0001 = styled.div`
	box-shadow: 0px 4px 30px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 157, 203, 0.33),0px -20px 50px  rgba(255, 255, 255, 0.53),10px 20px 100px  rgb(255, 135, 119);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 120px / 120px;
	position: absolute;
	left: 593px;
	top: 205px;
	right: 150px;
	bottom: 218px;
`;

const Bubble_0002 = styled.div`
	box-shadow: 0px 4px 20px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 180, 215, 0.33),0px -20px 20px  rgba(255, 255, 255, 0.23),10px 20px 100px  rgb(88, 61, 255);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 63px / 63px;
	position: absolute;
	left: 553px;
	top: 139px;
	right: 247px;
	bottom: 341px;
`;

const Bubble_0003 = styled.div`
	box-shadow: 0px 4px 20px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 180, 215, 0.33),0px -20px 20px  rgba(255, 255, 255, 0.23),10px 20px 100px  rgb(88, 61, 255);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 87px / 87px;
	position: absolute;
	left: 312px;
	top: 68px;
	right: 464px;
	bottom: 388px;
`;

const Bubble_0004 = styled.div`
	box-shadow: 0px 4px 20px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 180, 215, 0.33),0px -20px 20px  rgba(255, 255, 255, 0.23),10px 20px 100px  rgb(88, 61, 255);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 60px / 60px;
	position: absolute;
	left: 240px;
	top: 275px;
	right: 563px;
	bottom: 208px;
`;

const Bubble_0005 = styled.div`
	box-shadow: 0px 4px 80px  rgba(248, 0, 119, 0.48),0px 2px 10px  rgba(255, 255, 255, 0.58);
	background: radial-gradient(rgb(50, 68, 232), rgba(0, 2, 16, 0));
	border-radius: 20px / 20px;
	position: absolute;
	left: 653px;
	top: 151px;
	right: 190px;
	bottom: 372px;
`;

const Bubble_0006 = styled.div`
	box-shadow: 0px 4px 80px  rgba(248, 0, 119, 0.48),0px 2px 10px  rgba(255, 255, 255, 0.58);
	background: radial-gradient(rgb(50, 68, 232), rgba(0, 2, 16, 0));
	border-radius: 20px / 20px;
	position: absolute;
	left: 604px;
	top: 362px;
	right: 239px;
	bottom: 161px;
`;

const Bubble_0007 = styled.div`
	box-shadow: 0px 4px 80px  rgba(248, 0, 119, 0.48),0px 2px 10px  rgba(255, 255, 255, 0.58);
	background: radial-gradient(rgb(50, 68, 232), rgba(0, 2, 16, 0));
	border-radius: 20px / 20px;
	position: absolute;
	left: 256px;
	top: 65px;
	right: 587px;
	bottom: 458px;
`;

const Bubble_0008 = styled.div`
	box-shadow: 0px 4px 80px  rgba(248, 0, 119, 0.48),0px 2px 10px  rgba(255, 255, 255, 0.58);
	background: radial-gradient(rgb(50, 68, 232), rgba(0, 2, 16, 0));
	border-radius: 20px / 20px;
	position: absolute;
	left: 109px;
	top: 430px;
	right: 734px;
	bottom: 93px;
`;

const Bubble_0009 = styled.div`
	box-shadow: 0px 2px 10px  rgba(255, 255, 255, 0.58),0px -6px 10px  rgba(63, 209, 255, 0.67),10px 16px 20px  rgba(0, 133, 255, 0.95);
	background: radial-gradient(rgb(106, 228, 255), rgba(74, 147, 255, 0));
	border-radius: 60px / 60px;
	position: absolute;
	left: 64px;
	top: 164px;
	right: 739px;
	bottom: 319px;
`;

const Bubble_0010 = styled.div`
	box-shadow: 0px 4px 80px  rgb(35, 0, 248),0px 2px 10px  rgba(255, 255, 255, 0.58),10px 16px 20px  rgba(130, 5, 255, 0.95);
	background: radial-gradient(rgb(50, 68, 232), rgba(255, 255, 255, 0));
	border-radius: 60px / 60px;
	position: absolute;
	left: 803px;
	top: 372px;
	right: 0px;
	bottom: 111px;
`;

const Bubble_0011 = styled.div`
	box-shadow: 0px 2px 10px  rgba(255, 255, 255, 0.58),0px -6px 10px  rgba(63, 209, 255, 0.67),10px 16px 20px  rgba(0, 133, 255, 0.95);
	background: radial-gradient(rgb(106, 228, 255), rgba(74, 147, 255, 0));
	border-radius: 64px / 64px;
	position: absolute;
	left: 0px;
	top: 250px;
	right: 799px;
	bottom: 229px;
`;

const Bubble_0012 = styled.div`
	box-shadow: 0px 4px 30px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 148, 22, 0.33),0px -20px 50px  rgba(255, 255, 255, 0.53);
	background: radial-gradient(rgb(255, 184, 77), rgba(119, 43, 0, 0));
	border-radius: 101px / 101px;
	position: absolute;
	left: 97px;
	top: 273px;
	right: 665px;
	bottom: 169px;
`;

const Bubble_0013 = styled.div`
	box-shadow: 0px 40px 80px  rgba(35, 0, 248, 0.24),0px 2px 10px  rgba(255, 255, 255, 0.58),0px -20px 50px  rgba(124, 161, 255, 0.37),10px 16px 20px  rgba(210, 165, 255, 0.95);
	background: radial-gradient(rgb(131, 143, 255), rgba(227, 230, 255, 0));
	border-radius: 101px / 101px;
	position: absolute;
	left: 741px;
	top: 243px;
	right: 21px;
	bottom: 199px;
`;

const Bubble_0014 = styled.div`
	box-shadow: 0px 4px 30px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 157, 203, 0.33),0px -20px 50px  rgba(255, 255, 255, 0.53),10px 20px 100px  rgb(255, 135, 119);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 117px / 117px;
	position: absolute;
	left: 485px;
	top: 399px;
	right: 261px;
	bottom: 27px;
`;

const Bubble_0015 = styled.div`
	box-shadow: 0px 4px 30px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 157, 203, 0.33),0px -20px 50px  rgba(255, 255, 255, 0.53),10px 20px 100px  rgb(255, 135, 119);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 175px / 175px;
	position: absolute;
	left: 190px;
	top: 368px;
	right: 498px;
	bottom: 0px;
`;

const Bubble_0016 = styled.div`
	box-shadow: 0px 4px 30px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 157, 203, 0.33),0px -20px 50px  rgba(255, 255, 255, 0.53),10px 20px 100px  rgb(255, 135, 119);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 143px / 143px;
	position: absolute;
	left: 148px;
	top: 110px;
	right: 572px;
	bottom: 290px;
`;

const Bubble_0017 = styled.div`
	box-shadow: 0px 4px 30px  rgba(255, 255, 255, 0.76),0px 0px 20px  rgba(255, 255, 255, 0.13),60px 120px 80px  rgba(255, 157, 203, 0.33),0px -20px 50px  rgba(255, 255, 255, 0.53),10px 20px 100px  rgb(255, 135, 119);
	background: radial-gradient(rgb(255, 227, 211), rgba(179, 0, 183, 0));
	border-radius: 143px / 143px;
	position: absolute;
	left: 432px;
	top: 0px;
	right: 288px;
	bottom: 400px;
`;

const Investments = styled.div`
	width: 102px;
	height: 71px;
	position: absolute;
	left: 394px;
	top: 365px;
`;

const Time = styled.span`
	color: rgb(221, 221, 255);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: center;
	position: absolute;
	left: 24px;
	top: 51px;
	right: 17px;
	bottom: 0px;
`;

const Tittle = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 47px;
`;

const Value = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 32px;
	text-align: center;
	position: absolute;
	left: 10px;
	top: 21px;
	right: 9px;
	bottom: 18px;
`;

const Design = styled.div`
	width: 80px;
	height: 71px;
	position: absolute;
	left: 233px;
	top: 538px;
`;

const Time_0001 = styled.span`
	color: rgb(120, 120, 182);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: center;
	position: absolute;
	left: 13px;
	top: 51px;
	right: 6px;
	bottom: 0px;
`;

const Value_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 32px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 21px;
	right: 0px;
	bottom: 18px;
`;

const Title = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 12px;
	top: 0px;
	right: 11px;
	bottom: 47px;
`;

const Finance = styled.div`
	width: 67px;
	height: 43px;
	position: absolute;
	left: 470px;
	top: 161px;
`;

const Value_0002 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 19px;
	right: -6px;
	bottom: 0px;
`;

const Title_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 16px;
	text-align: center;
	position: absolute;
	left: 12px;
	top: 0px;
	right: 10px;
	bottom: 27px;
`;

const Business = styled.div`
	width: 58px;
	height: 43px;
	position: absolute;
	left: 623px;
	top: 354px;
`;

const Value_0003 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 19px;
	right: 0px;
	bottom: 0px;
`;

const Title_0002 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 16px;
	text-align: center;
	position: absolute;
	left: 4px;
	top: 0px;
	right: 2px;
	bottom: 27px;
`;

const Development = styled.div`
	width: 75px;
	height: 43px;
	position: absolute;
	left: 182px;
	top: 272px;
`;

const Value_0004 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 7px;
	top: 19px;
	right: 10px;
	bottom: 0px;
`;

const Title_0003 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 16px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 27px;
`;

const Title_0004 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 34px;
	font-family: Poppins, sans-serif;
	font-weight: 400;
	line-height: 44px;
	text-align: left;
	position: absolute;
	left: 59px;
	top: calc((calc((50% + -427px)) - 1px));
`;

const Bubble_0018 = styled.div`
	width: 105px;
	height: 105px;
	box-shadow: 0px 40px 80px  rgba(35, 0, 248, 0.24),0px 2px 10px  rgba(255, 255, 255, 0.58),0px -20px 50px  rgba(124, 161, 255, 0.37),10px 16px 20px  rgba(130, 5, 255, 0.95);
	background: radial-gradient(rgb(131, 143, 255), rgba(227, 230, 255, 0));
	border-radius: 105px / 105px;
	position: absolute;
	left: calc((calc((50% + 650px)) - 53px));
	top: calc((calc((50% + -228px)) - 53px));
`;

const Bubble_0019 = styled.div`
	box-shadow: 0px 40px 80px  rgba(35, 0, 248, 0.53),0px 2px 10px  rgba(255, 255, 255, 0.58),0px -20px 50px  rgba(124, 161, 255, 0.37),10px 16px 20px  rgba(130, 5, 255, 0.95);
	background: radial-gradient(rgb(131, 143, 255), rgba(227, 230, 255, 0));
	border-radius: 75px / 75px;
	position: absolute;
	left: 1332px;
	top: 656px;
	right: 513px;
	bottom: 349px;
`;

const Bubble_0020 = styled.div`
	width: 61px;
	height: 61px;
	box-shadow: 0px 50px 80px  rgba(35, 0, 248, 0.31),0px 2px 10px  rgba(255, 255, 255, 0.58),10px 16px 20px  rgba(130, 5, 255, 0.95);
	background: radial-gradient(rgb(50, 68, 232), rgba(255, 255, 255, 0));
	border-radius: 61px / 61px;
	position: absolute;
	left: calc((calc((50% + -261px)) - 31px));
	top: calc((calc((50% + 261px)) - 31px));
`;

const Bubble_0021 = styled.div`
	width: 47px;
	height: 47px;
	box-shadow: 0px 4px 80px  rgba(35, 0, 248, 0.46),0px 2px 10px  rgba(255, 255, 255, 0.58),10px 16px 20px  rgba(130, 5, 255, 0.95);
	background: radial-gradient(rgb(50, 68, 232), rgba(0, 2, 16, 0));
	border-radius: 47px / 47px;
	position: absolute;
	left: calc((calc((50% + -320px)) - 24px));
	top: calc((calc((50% + -298px)) - 24px));
`;

const Bubble_0022 = styled.div`
	width: 47px;
	height: 47px;
	box-shadow: 0px 4px 80px  rgba(35, 0, 248, 0.46),0px 2px 10px  rgba(255, 255, 255, 0.58),10px 16px 20px  rgba(130, 5, 255, 0.95);
	background: radial-gradient(rgb(50, 68, 232), rgba(0, 2, 16, 0));
	border-radius: 47px / 47px;
	position: absolute;
	left: calc((calc((50% + 621px)) - 24px));
	top: calc((calc((50% + 269px)) - 24px));
`;

const Timeline = styled.span`
	color: rgb(61, 61, 96);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: "Open Sans", sans-serif;
	font-weight: 700;
	letter-spacing: 5px;
	line-height: 16px;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: calc((calc((50% + 162px)) - 41px));
	top: 95px;
`;

const Timeline_0001 = styled.div`
	width: 351px;
	height: 36px;
	position: absolute;
	left: calc((calc((50% + 163px)) - 176px));
	top: 126px;
`;

const BackgroundElement = styled.div`
	background-color: white;
	border-radius: 100px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const DateRangePicker = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 20px;
	box-sizing: border-box;
	position: absolute;
	left: 3px;
	top: 2px;
	right: 3px;
	bottom: 2px;
`;

const TimePeriod = styled.div`
	width: 53px;
	height: 32px;
	position: relative;
`;

const Period = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 2px)) - 10px));
	right: 0px;
`;

const Hover = styled.div`
	background-color: rgb(50, 71, 229);
	border-radius: 16px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Period_0002 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 13px;
	font-family: Mulish, sans-serif;
	font-weight: 700;
	text-align: center;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 8px));
	right: 0px;
`;

const NavigationBar = styled.div`
	height: 60px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
`;

const Background_0001 = styled.div`
	background-color: white;
	position: absolute;
    width: 1947px;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Search = styled.div`
	width: 520px;
	height: 32px;
	position: absolute;
	left: calc((calc((50% + -300px)) - 260px));
	top: calc((calc((50% + 0px)) - 16px));
`;

const Input = styled.div`
	width: 520px;
	height: 32px;
	background-color: rgb(238, 240, 250);
	border-radius: 8px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Icon = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 0px)) - 12px));
	right: 7px;
`;

const Tab = styled.div`
	background-color: rgb(87, 86, 179);
	position: absolute;
	left: 1169px;
	top: 57px;
	right: 645px;
	bottom: 0px;
`;

const Menu = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 84px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + 353px)) - 286px));
	top: calc((calc((50% + 0px)) - 12px));
	width: 571px;
	height: 24px;
`;

const Label = styled.span`
	color: rgb(132, 132, 160);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
`;

const Label_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
`;

const Profile = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 0px)) - 12px));
	right: 109px;
`;

const Option = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 0px)) - 12px));
	right: 70px;
`;

const Name = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: Archivo, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 161px;
	position: absolute;
	left: 84px;
	top: calc((calc((50% + 0px)) - 11px));
`;

const WstfLogo1 = styled.div`
	width: 40px;
	height: 40px;
	overflow: hidden;
	position: absolute;
	left: 35px;
	top: 10px;
`;

const Group = styled.div`
	width: 39px;
	height: 39px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 0px;
	top: 0px;
`;

const Vector = styled.img`
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Footer = styled.div`
	height: 38px;
	position: absolute;
	left: 0px;
	right: 0px;
	bottom: 0px;
`;

const Bg = styled.div`
	background-color: white;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const OrionDataVisualisation = styled.span`
	color: rgb(90, 90, 137);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: 67px;
	top: calc((calc((50% + 0px)) - 8px));
`;

const _2019 = styled.span`
	color: rgb(90, 90, 137);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: right;
	text-transform: uppercase;
	position: absolute;
	top: calc((calc((50% + 0px)) - 8px));
	right: 67px;
`;

const InformerTrendGoods = styled.div`
	height: 146px;
	position: absolute;
	left: 782px;
	right: 1038px;
	bottom: 89px;
`;

const Value_0005 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 60px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	letter-spacing: -2px;
	line-height: 80px;
	text-align: center;
	position: absolute;
	left: -3px;
	top: 66px;
`;

const Title_0005 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: center;
	text-transform: uppercase;
	position: absolute;
	left: 9px;
	top: 62px;
`;

const Icon_0001 = styled.div`
	width: 46px;
	height: 46px;
	position: absolute;
	left: 27px;
	top: 0px;
`;

const Stroke = styled.div`
	width: 46px;
	height: 46px;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	background-color: white;
	border-radius: 8px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Favorite = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: 11px;
	top: 11px;
`;

const InformerTrendGoods_0001 = styled.div`
	height: 146px;
	position: absolute;
	left: 1072px;
	right: 748px;
	bottom: 89px;
`;

const Value_0006 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 60px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	letter-spacing: -2px;
	line-height: 80px;
	text-align: center;
	position: absolute;
	left: -44px;
	top: 66px;
`;

const Title_0006 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: center;
	text-transform: uppercase;
	position: absolute;
	left: -1px;
	top: 62px;
`;

const Eye = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: 11px;
	top: 11px;
`;

const InformerTrendGoods_0002 = styled.div`
	height: 146px;
	position: absolute;
	left: 1362px;
	right: 458px;
	bottom: 89px;
`;

const Value_0007 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 60px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	letter-spacing: -2px;
	line-height: 80px;
	text-align: center;
	position: absolute;
	left: -2px;
	top: 66px;
`;

const Title_0007 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: center;
	text-transform: uppercase;
	position: absolute;
	left: -2px;
	top: 62px;
`;

const Chart = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: 11px;
	top: 11px;
`;

const PanelGroup = styled.div`
	width: 46px;
	height: 298px;
	position: absolute;
	left: 1814px;
	top: 391px;
`;

const Zoom = styled.div`
	width: 46px;
	height: 92px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Bg_0001 = styled.div`
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	background-color: white;
	border-radius: 8px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Plus = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 12px));
	top: 10px;
`;

const Minus = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 12px));
	bottom: 10px;
`;

const Map = styled.div`
	width: 46px;
	height: 46px;
	position: absolute;
	left: 0px;
	top: 106px;
`;

const Map_0001 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 12px));
	top: calc((calc((50% + 0px)) - 12px));
`;

const Tool = styled.div`
	width: 46px;
	height: 132px;
	position: absolute;
	left: 0px;
	top: 166px;
`;

const Node = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 12px));
	top: 10px;
`;

const Element = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 12px));
	top: calc((calc((50% + 0px)) - 12px));
`;

const Path = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 12px));
	bottom: 10px;
`;

const WidgetMSizeCombinedCircleChartWithDynamicTable = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 30px;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	border-radius: 10px;
	background-color: white;
	box-sizing: border-box;
	padding: 20px 0px;
	position: absolute;
	left: 60px;
	top: 166px;
	width: 290px;
	height: 401px;
`;

const Graph = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 16px;
	border-radius: 10px;
	background-color: white;
	box-sizing: border-box;
	padding: 0px 30px;
`;

const ChartDoubleBigCircleChart = styled.div`
	width: 146px;
	height: 146px;
	position: relative;
`;

const Chart_0001 = styled.div`
	width: 146px;
	height: 146px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const ChartBg = styled.img`
	object-fit: contain;
	position: absolute;
	left: 4px;
	top: 142px;
	right: 3px;
	bottom: -135px;
	transform: rotate(-90deg);
	transform-origin: top left;
`;

const ChartBg_0001 = styled.img`
	object-fit: contain;
	position: absolute;
	left: 22px;
	top: 124px;
	right: 21px;
	bottom: -81px;
	transform: rotate(-90deg);
	transform-origin: top left;
`;

const Progress1 = styled.img`
	object-fit: contain;
	position: absolute;
	left: 19px;
	top: 127px;
	right: 19px;
	bottom: -89px;
	transform: rotate(-90deg);
	transform-origin: top left;
`;

const Progress2 = styled.img`
	object-fit: contain;
	position: absolute;
	left: 96px;
	top: -18px;
	right: 0px;
	bottom: -146px;
	transform: rotate(-307deg);
	transform-origin: top left;
`;

const Progress3 = styled.img`
    position: relative;
    left: 79px;
    top: 3px;
    transform: rotate(13deg);
`;

const Bg_0004 = styled.div`
	background-color: rgb(244, 246, 255);
	border-radius: 59px / 59px;
	position: absolute;
	left: 44px;
	top: 43px;
	right: 43px;
	bottom: 44px;
`;

const Icon_0004 = styled.img`
	width: 26px;
	height: 26px;
	object-fit: cover;
	position: absolute;
	left: 61px;
	top: 59px;
`;

const Info = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	box-sizing: border-box;
`;

const Title_0008 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	box-sizing: border-box;
`;

const Name_0001 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 32px;
	text-align: center;
	width: 231px;
`;

const Value_0008 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 6px;
	box-sizing: border-box;
`;

const Amount = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 22px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 36px;
	text-align: center;
`;

const Indicator = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	align-self: stretch;
	height: 26px;
	box-sizing: border-box;
`;

const ArrowUp = styled.div`
	width: 14px;
	height: 24px;
	overflow: hidden;
	position: relative;
`;

const Arrow = styled.svg`
	width: 12px;
	height: 8px;
	position: absolute;
	left: 1px;
	top: 9px;
	right: 1px;
	bottom: 7px;
`;

const Percent = styled.span`
	color: rgb(0, 185, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: center;
	width: 24px;
	min-height: 28px;
`;

const Detail = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 16px;
	text-align: center;
	width: 236px;
	opacity: 0.6;
`;

const Table = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 11px;
	border-radius: 10px;
	background-color: white;
	box-sizing: border-box;
	padding: 0px 30px;
`;

const Row = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 16px;
	box-sizing: border-box;
`;

const Name_0002 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
	width: 88px;
`;

const Amount_0001 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
	width: 42px;
	opacity: 0.6;
`;

const Graph_0001 = styled.div`
	width: 68px;
	height: 21px;
	position: relative;
`;

const Column = styled.div`
	width: 17px;
	height: 21px;
	background-color: rgb(219, 223, 241);
	border-radius: 1px;
	position: absolute;
	left: 0px;
	top: 0px;
	opacity: 0.7;
`;

const Column_0001 = styled.div`
	width: 14px;
	height: 21px;
	background-color: rgb(219, 223, 241);
	border-radius: 1px;
	position: absolute;
	left: 19px;
	top: 0px;
	opacity: 0.7;
`;

const Column_0002 = styled.div`
	width: 14px;
	height: 21px;
	background-color: rgb(219, 223, 241);
	border-radius: 1px;
	position: absolute;
	left: 35px;
	top: 0px;
	opacity: 0.7;
`;

const Column_0003 = styled.div`
	width: 17px;
	height: 21px;
	background-color: rgb(219, 223, 241);
	border-radius: 1px;
	position: absolute;
	left: 51px;
	top: 0px;
	opacity: 0.7;
`;

const Chart_0002 = styled.img`
	width: 68px;
	height: 11px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 5px;
`;

const Chart_0004 = styled.img`
	width: 67px;
	height: 8px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 6px;
`;

const WidgetMSizeOmpositeIndex = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 18px;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	border-radius: 10px;
	background-color: rgb(134, 118, 255);
	box-sizing: border-box;
	padding: 20px 30px;
	position: absolute;
	left: 60px;
	top: calc((calc((50% + 181px)) - 126px));
	width: 290px;
	height: 252px;
`;

const Informer = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 2px;
	box-sizing: border-box;
`;

const Title_0009 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	width: 134px;
	box-sizing: border-box;
`;

const Name_0005 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	width: 135px;
`;

const Amount_0004 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 34px;
	font-family: Poppins, sans-serif;
	font-weight: 400;
	line-height: 44px;
	text-align: left;
`;

const Percent_0001 = styled.span`
	color: rgb(56, 242, 97);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
	width: 37px;
	min-height: 26px;
`;

const Detail_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 16px;
	text-align: left;
	width: 236px;
	opacity: 0.6;
`;

const Divider = styled.img`
	width: 230px;
	height: 0px;
	object-fit: cover;
`;

const Name_0006 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	width: 129px;
`;

const TableIndicatorTable = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 14px;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	border-radius: 10px;
	background-color: white;
	box-sizing: border-box;
	padding: 20px 30px;
	position: absolute;
	left: 60px;
	top: calc((calc((50% + 399px)) - 64px));
	width: 290px;
	height: 128px;
`;

const Row_0003 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 6px;
	box-sizing: border-box;
`;

const Summary = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 6px;
	box-sizing: border-box;
`;

const Name_0007 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
	width: 98px;
`;

const Amount_0006 = styled.span`
	color: rgb(146, 146, 193);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
	width: 50px;
`;

const Summary_0001 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
	width: 50px;
`;

const Status = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	height: 20px;
	box-sizing: border-box;
`;

const Arro = styled.svg`
	width: 12px;
	height: 8px;
	position: absolute;
	left: 13px;
	top: 17px;
	right: -11px;
	bottom: -1px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;
