import React from "react";
import styled from "@emotion/styled";
/**
 * `<WorldHexagonMap>` ('World hexagon map')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <WorldHexagonMap/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/11ac7f25-e512-47ba-bc4b-256e1675d67e)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/1568:5634 -->
 */
export function WORLDHEXAGONMAP() {
  return (
    <RootWrapperWorldHexagonMap>
      {/* <WidgetLSizeTimelineChart> */}
        {/* <Info>
          <Value>
            <Value_0001>
              <Title>Sales Figures</Title>
              <Value_0002>$10,430</Value_0002>
            </Value_0001>
          </Value>
        </Info> */}
        {/* <Graph>
          <Chart>
            <Column />
            <Column_0001 />
            <Column_0002 />
            <Column_0003 />
            <Column_0004 />
            <Column_0005 />
            <Column_0004 />
            <Column_0007 />
            <Column_0008 />
            <Column_0003 />
            <Column_0003 />
            <Column_0007 />
            <Column_0003 />
            <Column_0013 />
            <Column_0014 />
            <Column_0015 />
            <Column_0016 />
            <Column_0014 />
            <Column_0018 />
            <Column_0019 />
            <Column_0020 />
            <Column_0021 />
            <Column_0022 />
            <Column_0023 />
            <Column_0024 />
            <Column_0018 />
            <Column_0026 />
            <Column_0026 />
            <Column_0028 />
            <Column_0026 />
            <Column_0016 />
            <Column_0031 />
            <Column_0014 />
            <Column_0014 />
            <Column_0016 />
            <Column_0014 />
            <Column_0013 />
            <Column_0014 />
            <Column_0015 />
            <Column_0016 />
            <Column_0014 />
            <Column_0014 />
            <Column_0042 />
            <Column_0031 />
            <Column_0015 />
            <Column_0015 />
            <Column />
            <Column_0001 />
            <Column_0002 />
            <Column_0003 />
            <Column_0050 />
            <Column_0050 />
            <Column_0052 />
            <Column_0050 />
            <Column_0054 />
            <Column_0055 />
            <Column_0015 />
            <Column_0015 />
            <Column_0054 />
            <Column_0015 />
            <Column_0060 />
            <Column_0015 />
            <Column_0013 />
            <Column_0054 />
            <Column_0054 />
            <Column_0054 />
            <Column_0054 />
            <Column_0015 />
            <Column_0068 />
            <Column_0068 />
            <Column_0070 />
            <Column_0071 />
          </Chart>
          <Line>
            <Bg />
            <Cian />
            <Yellow />
          </Line>
  </Graph> */}
      {/* </WidgetLSizeTimelineChart> */}
      {/* <NavigationBar>
        <Background />
        <Search>
          <Input />
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8f283fab-14ff-4ef3-86f4-9ff800aa8536"
            alt="icon"
          />
        </Search>
        <Tab />
        <Menu>
          <Label>Statistics</Label>
          <Label_0001>Overview</Label_0001>
          <Label>Dashboard</Label>
          <Label>Analytics</Label>
        </Menu>
        <Profile
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6bf62539-0eca-4c51-ae22-77fea9cb8aff"
          alt="icon"
        />
        <Option
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/19e0a028-07a3-4937-b10e-b7d5241a9aa2"
          alt="icon"
        />
</NavigationBar> */}
      {/* <Footer>
        <Bg_0001 />
        <OrionDataVisualisation>Orion data visualisation</OrionDataVisualisation>
        <_2019>2019</_2019>
      </Footer> */}
      {/* <SideIndicators>
        <InformerInfoWithIcon>
          <Icon_0001>
            <Background_0001 />
            <Activity
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1b8b07d3-9786-4438-ae7e-e8f55ea654d9"
              alt="icon"
            />
          </Icon_0001>
          <Info_0001>
            <Title_0001>Total earning</Title_0001>
            <Amount>
              <Value_0003>540,549</Value_0003>
            </Amount>
          </Info_0001>
        </InformerInfoWithIcon>
        <InformerInfoWithIcon>
          <Icon_0001>
            <Background_0002 />
            <Crown
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b56a4741-91f4-459b-8452-285ffee47b81"
              alt="icon"
            />
          </Icon_0001>
          <Info_0001>
            <Title_0001>Sales</Title_0001>
            <Amount>
              <Value_0003>1,205,677</Value_0003>
            </Amount>
          </Info_0001>
        </InformerInfoWithIcon>
        <InformerInfoWithIcon>
          <Icon_0001>
            <Background_0003 />
            <Chart_0001
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/db72b37b-82a8-49ec-b0ca-23db32a6e012"
              alt="icon"
            />
          </Icon_0001>
          <Info_0001>
            <Title_0001>Purchase</Title_0001>
            <Amount>
              <Value_0003>48,430,039</Value_0003>
            </Amount>
          </Info_0001>
        </InformerInfoWithIcon>
      </SideIndicators> */}
      {/* <WidgetMSizeBigCircleChart>
        <Chart_0002>
          <Percent>27%</Percent>
          <Background_0004 />
          <Progress
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bd8006a7-4605-484e-b82f-a17690dac4f7"
            alt="image from ellipse"
          />
        </Chart_0002>
        <Info_0004>
          <Amount_0003>92,980</Amount_0003>
          <Detail>Active users</Detail>
        </Info_0004>
      </WidgetMSizeBigCircleChart> */}
      {/* <WidgetMSizeBigCircleChart_0001>
        <Chart_0002>
          <Percent>67%</Percent>
          <Background_0004 />
          <Progress
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/71004beb-febe-4871-97ab-b7b408fa5a21"
            alt="image from ellipse"
          />
        </Chart_0002>
        <Info_0004>
          <Amount_0003>22,652</Amount_0003>
          <Detail>New users</Detail>
        </Info_0004>
      </WidgetMSizeBigCircleChart_0001> */}
      {/* <HexMap /> */}
      {/* <MapPinPinWithName>
        <Tooltip>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7ff06fb9-cfc7-4f68-95fd-e1b1b85d69ea"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Chicago</Title_0004>
            <Amount_0005>98,320,300</Amount_0005>
          </Info_0001>
        </Tooltip>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName> */}
      {/* <MapPinPinWithName_0001>
        <Tooltip_0001>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0ff5be92-bf76-4731-8fcf-460494c9c99f"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Manaus</Title_0004>
            <Amount_0005>12,320,300</Amount_0005>
          </Info_0001>
        </Tooltip_0001>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0001> */}
      {/* <MapPinPinWithName_0002>
        <Tooltip_0002>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8795f105-7f23-4a9a-87f1-32bc2d935801"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Berlin</Title_0004>
            <Amount_0005>76,541,106</Amount_0005>
          </Info_0001>
        </Tooltip_0002>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0002> */}
      {/* <MapPinPinWithName_0003>
        <Tooltip_0003>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2282bd74-94cc-49b6-b908-91c77960f906"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Giza</Title_0004>
            <Amount_0005>10,547,980</Amount_0005>
          </Info_0001>
        </Tooltip_0003>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0003> */}
      {/* <MapPinPinWithName_0004>
        <Tooltip>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c36fe32e-ff82-429d-a7ff-74061954bd92"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Shanghai</Title_0004>
            <Amount_0005>239,570,110</Amount_0005>
          </Info_0001>
        </Tooltip>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0004> */}
      {/* <MapPinPinWithName_0005>
        <Tooltip_0005>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c86c98b4-b20c-4a7d-92a5-0f11e1701b0d"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Queensland</Title_0004>
            <Amount_0005>6,097,321</Amount_0005>
          </Info_0001>
        </Tooltip_0005>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0005> */}
      {/* <Footer>
        <Bg_0001 />
        <Description>Orion data visualisation</Description>
        <_2019>2022</_2019>
      </Footer>
      <Amount_0011>2,431,340</Amount_0011> */}
      {/* <Title_0010>
        <Name>All users</Name>
        <Detail_0002>
          <Detail_0003>Detail</Detail_0003>
          <Arow
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4c923906-4112-407f-a4fc-1fdf6fd06b4c"
            alt="icon"
          />
        </Detail_0002>
      </Title_0010> */}
      <WidgetLSizeGlobalStatistic>
        <Header>
          <Title_0011>Sales Figures</Title_0011>
          <Legend>
            <Shape />
            <MarketingSales>Sales</MarketingSales>
          </Legend>
          <Legend>
            <Shape_0001 />
            <MarketingSales>Users</MarketingSales>
          </Legend>
          <Legend>
            <Shape_0002 />
            <MarketingSales>Product</MarketingSales>
          </Legend>
          <Legend>
            <Shape_0003 />
            <MarketingSales>Team</MarketingSales>
          </Legend>
        </Header>
        <Graph_0001>
          <Chart_0004>
            <YAxis>
              <_1K>1k</_1K>
              <_0>0</_0>
              <_200>200</_200>
              <_400>400</_400>
              <_600>600</_600>
              <_800>800</_800>
            </YAxis>
            <XAxis>
              <Dec>
                <Name_0001>Dec</Name_0001>
                <Shape_0004 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44063e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0004>
              </Dec>
              <Nov>
                <Name_0002>Nov</Name_0002>
                <Shape_0004 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44062e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0004>
              </Nov>
              <Oct>
                <Name_0003>Oct</Name_0003>
                <Shape_0006 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44063e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0006>
              </Oct>
              <Sep>
                <Name_0001>Sep</Name_0001>
                <Shape_0007 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44063e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0007>
              </Sep>
              <Aug>
                <Name_0005>Aug</Name_0005>
                <Shape_0004 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44063e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0004>
              </Aug>
              <Jul>
                <Name_0006>Jul</Name_0006>
                <Shape_0009 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44063e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0009>
              </Jul>
              <Jun>
                <Name_0007>Jun</Name_0007>
                <Shape_0010 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0 384.2L2.44063e-14 0L1.14496 0L1.14496 384.2L0 384.2Z"
                  />
                </Shape_0010>
              </Jun>
              <May>
                <Name_0001>May</Name_0001>
                <Shape_0011 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0.013011 384.2L0.013011 0L1.13195 0L1.13195 384.2L0.013011 384.2Z"
                  />
                </Shape_0011>
              </May>
              <Apr>
                <Name_0009>Apr</Name_0009>
                <Shape_0012 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0.0130109 384.2L0.0130109 0L1.13195 0L1.13195 384.2L0.0130109 384.2Z"
                  />
                </Shape_0012>
              </Apr>
              <Mar>
                <Name_0010>Mar</Name_0010>
                <Shape_0013 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0.0130109 384.2L0.0130109 0L1.13195 0L1.13195 384.2L0.0130109 384.2Z"
                  />
                </Shape_0013>
              </Mar>
              <Feb>
                <Name_0007>Feb</Name_0007>
                <Shape_0014 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0.0130109 384.2L0.0130109 0L1.13195 0L1.13195 384.2L0.0130109 384.2Z"
                  />
                </Shape_0014>
              </Feb>
              <Jan>
                <Name_0007>Jan</Name_0007>
                <Shape_0010 xmlns="http://www.w3.org/2000/svg">
                  <path
                    fill="rgb(241, 241, 245)"
                    d="M0.0130109 384.2L0.0130109 0L1.13195 0L1.13195 384.2L0.0130109 384.2Z"
                  />
                </Shape_0010>
              </Jan>
            </XAxis>
          </Chart_0004>
          <Data>
            <Bubble />
            <Bubble_0001 />
            <Bubble_0002 />
            <Bubble_0003 />
            <Bubble_0004 />
            <Bubble_0005 />
            <Bubble_0006 />
            <Bubble_0007 />
            <Bubble_0008 />
            <Bubble_0009 />
            <Bubble_0010 />
            <Bubble_0011>
              <Bubble_0012 />
              <Value_0006>$27632</Value_0006>
            </Bubble_0011>
            <Bubble_0013>
              <Bubble_0014 />
              <Value_0007>$27632</Value_0007>
            </Bubble_0013>
            <Bubble_0015>
              <Bubble_0016 />
              <Value_0008>$27632</Value_0008>
              <Text>August</Text>
            </Bubble_0015>
          </Data>
        </Graph_0001>
      </WidgetLSizeGlobalStatistic>
      <Name_0013>WASSERSTOFF</Name_0013>
      {/* <WstfLogo1>
        <Group>
          <Vector
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/03671005-5c65-41c8-9cc7-d70761bd7b17"
            alt="icon"
          />
          <Vector
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/aa32a219-4f20-4aba-a30d-7162b30fd001"
            alt="icon"
          />
        </Group>
      </WstfLogo1> */}
    </RootWrapperWorldHexagonMap>
  );
}

const RootWrapperWorldHexagonMap = styled.div`
	min-height: 100vh;
	border-radius: 10px;
	position: relative;
    right: 300px;
    bottom: 120px;
`;

// const WidgetLSizeTimelineChart = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 17px;
// 	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
// 	border-radius: 10px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	position: absolute;
// 	left: calc((calc((50% + 0px)) - 900px));
// 	bottom: 66px;
// 	width: 1800px;
// 	height: 86px;
// `;

// const Info = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: column;
// 	align-items: center;
// 	flex: none;
// 	gap: 10px;
// 	border-radius: 10px;
// 	width: 132px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 0px 32px;
// `;

// const Value = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	flex: none;
// 	gap: 59px;
// 	box-sizing: border-box;
// `;

// const Value_0001 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: column;
// 	align-items: flex-start;
// 	flex: none;
// 	gap: 2px;
// 	box-sizing: border-box;
// `;

// const Title = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 14px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 400;
// 	line-height: 20px;
// 	text-align: left;
// `;

// const Value_0002 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 22px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 600;
// 	line-height: 36px;
// 	text-align: left;
// `;

// const Graph = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: column;
// 	align-items: center;
// 	flex: none;
// 	gap: 2px;
// 	border-radius: 10px;
// 	width: 1651px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 20px 32px;
// `;

// const Chart = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: flex-end;
// 	flex: none;
// 	gap: 2px;
// 	box-sizing: border-box;
// `;

// const Column = styled.div`
// 	width: 20px;
// 	height: 25px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0001 = styled.div`
// 	width: 20px;
// 	height: 27px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0002 = styled.div`
// 	width: 20px;
// 	height: 28px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0003 = styled.div`
// 	width: 20px;
// 	height: 31px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0004 = styled.div`
// 	width: 21px;
// 	height: 31px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0005 = styled.div`
// 	width: 21px;
// 	height: 24px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0007 = styled.div`
// 	width: 20px;
// 	height: 38px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0008 = styled.div`
// 	width: 20px;
// 	height: 36px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0013 = styled.div`
// 	width: 20px;
// 	height: 24px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0014 = styled.div`
// 	width: 20px;
// 	height: 14px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0015 = styled.div`
// 	width: 20px;
// 	height: 19px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0016 = styled.div`
// 	width: 20px;
// 	height: 18px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0018 = styled.div`
// 	width: 20px;
// 	height: 14px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0019 = styled.div`
// 	width: 20px;
// 	height: 16px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0020 = styled.div`
// 	width: 20px;
// 	height: 17px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0021 = styled.div`
// 	width: 20px;
// 	height: 19px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0022 = styled.div`
// 	width: 20px;
// 	height: 25px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0023 = styled.div`
// 	width: 20px;
// 	height: 27px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0024 = styled.div`
// 	width: 20px;
// 	height: 28px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0026 = styled.div`
// 	width: 21px;
// 	height: 14px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0028 = styled.div`
// 	width: 21px;
// 	height: 24px;
// 	background-color: rgb(255, 112, 139);
// `;

// const Column_0031 = styled.div`
// 	width: 20px;
// 	height: 17px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0042 = styled.div`
// 	width: 20px;
// 	height: 16px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0050 = styled.div`
// 	width: 21px;
// 	height: 19px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0052 = styled.div`
// 	width: 21px;
// 	height: 13px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0054 = styled.div`
// 	width: 20px;
// 	height: 22px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0055 = styled.div`
// 	width: 20px;
// 	height: 21px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0060 = styled.div`
// 	width: 20px;
// 	height: 13px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0068 = styled.div`
// 	width: 20px;
// 	height: 9px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0070 = styled.div`
// 	width: 20px;
// 	height: 10px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Column_0071 = styled.div`
// 	width: 20px;
// 	height: 11px;
// 	background-color: rgb(219, 223, 241);
// `;

// const Line = styled.div`
// 	width: 1593px;
// 	height: 6px;
// 	position: relative;
// `;

// const Bg = styled.div`
// 	background-color: rgb(134, 118, 255);
// 	border-radius: 100px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	right: 0px;
// 	bottom: 0px;
// `;

// const Cian = styled.div`
// 	background-color: rgb(255, 112, 139);
// 	border-radius: 100px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	right: 869px;
// 	bottom: 0px;
// `;

// const Yellow = styled.div`
// 	background-color: rgb(255, 166, 63);
// 	border-radius: 100px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	right: 1353px;
// 	bottom: 0px;
// `;

// const NavigationBar = styled.div`
// 	height: 60px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	right: 0px;
// `;

// const Background = styled.div`
// 	background-color: white;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	right: 0px;
// 	bottom: 0px;
// `;

// const Search = styled.div`
// 	width: 520px;
// 	height: 32px;
// 	position: absolute;
// 	left: calc((calc((50% + -300px)) - 260px));
// 	top: calc((calc((50% + 0px)) - 16px));
// `;

// const Input = styled.div`
// 	width: 520px;
// 	height: 32px;
// 	background-color: rgb(238, 240, 250);
// 	border-radius: 8px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// `;

// const Icon = styled.img`
// 	width: 24px;
// 	height: 24px;
// 	object-fit: cover;
// 	position: absolute;
// 	top: calc((calc((50% + 0px)) - 12px));
// 	right: 7px;
// `;

// const Tab = styled.div`
// 	background-color: rgb(87, 86, 179);
// 	position: absolute;
// 	left: 1169px;
// 	top: 57px;
// 	right: 645px;
// 	bottom: 0px;
// `;

// const Menu = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 84px;
// 	box-sizing: border-box;
// 	position: absolute;
// 	left: calc((calc((50% + 353px)) - 286px));
// 	top: calc((calc((50% + 0px)) - 12px));
// 	width: 571px;
// 	height: 24px;
// `;

// const Label = styled.span`
// 	color: rgb(132, 132, 160);
// 	text-overflow: ellipsis;
// 	font-size: 16px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 300;
// 	line-height: 24px;
// 	text-align: left;
// `;

// const Label_0001 = styled.span`
// 	color: black;
// 	text-overflow: ellipsis;
// 	font-size: 16px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 300;
// 	line-height: 24px;
// 	text-align: left;
// `;

// const Profile = styled.img`
// 	width: 24px;
// 	height: 24px;
// 	object-fit: cover;
// 	position: absolute;
// 	top: calc((calc((50% + 0px)) - 12px));
// 	right: 110px;
// `;

// const Option = styled.img`
// 	width: 24px;
// 	height: 24px;
// 	object-fit: cover;
// 	position: absolute;
// 	top: calc((calc((50% + 0px)) - 12px));
// 	right: 60px;
// `;

// const Footer = styled.div`
// 	height: 38px;
// 	position: absolute;
// 	left: 0px;
// 	right: 0px;
// 	bottom: 0px;
// `;

// const Bg_0001 = styled.div`
// 	background-color: white;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	right: 0px;
// 	bottom: 0px;
// `;

// const OrionDataVisualisation = styled.span`
// 	color: rgb(90, 90, 137);
// 	text-overflow: ellipsis;
// 	font-size: 10px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 700;
// 	letter-spacing: 2px;
// 	line-height: 16px;
// 	text-align: left;
// 	text-transform: uppercase;
// 	position: absolute;
// 	left: 67px;
// 	top: calc((calc((50% + 0px)) - 8px));
// `;

// const _2019 = styled.span`
// 	color: rgb(90, 90, 137);
// 	text-overflow: ellipsis;
// 	font-size: 10px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 700;
// 	letter-spacing: 2px;
// 	line-height: 16px;
// 	text-align: right;
// 	text-transform: uppercase;
// 	position: absolute;
// 	top: calc((calc((50% + 0px)) - 8px));
// 	right: 67px;
// `;

// const SideIndicators = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: column;
// 	align-items: flex-start;
// 	gap: 30px;
// 	box-sizing: border-box;
// 	position: absolute;
// 	left: 60px;
// 	top: 406px;
// 	width: 218px;
// 	height: 270px;
// `;

// const InformerInfoWithIcon = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	flex: none;
// 	gap: 26px;
// 	box-sizing: border-box;
// `;

// const Icon_0001 = styled.div`
// 	width: 70px;
// 	height: 70px;
// 	position: relative;
// `;

// const Background_0001 = styled.div`
// 	width: 70px;
// 	height: 70px;
// 	background-color: rgb(134, 118, 255);
// 	border-radius: 20px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// `;

// const Activity = styled.img`
// 	width: 32px;
// 	height: 32px;
// 	object-fit: cover;
// 	position: absolute;
// 	left: 20px;
// 	top: 20px;
// `;

// const Info_0001 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: column;
// 	align-items: flex-start;
// 	flex: none;
// 	box-sizing: border-box;
// `;

// const Title_0001 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 20px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 400;
// 	line-height: 32px;
// 	text-align: left;
// `;

// const Amount = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	flex: none;
// 	gap: 4px;
// 	box-sizing: border-box;
// `;

// const Value_0003 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 20px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 600;
// 	line-height: 32px;
// 	text-align: left;
// `;

// const Background_0002 = styled.div`
// 	width: 70px;
// 	height: 70px;
// 	background-color: rgb(102, 200, 255);
// 	border-radius: 20px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// `;

// const Crown = styled.img`
// 	width: 32px;
// 	height: 32px;
// 	object-fit: cover;
// 	position: absolute;
// 	left: 20px;
// 	top: 20px;
// `;

// const Background_0003 = styled.div`
// 	width: 70px;
// 	height: 70px;
// 	background-color: rgb(255, 144, 102);
// 	border-radius: 20px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// `;

// const Chart_0001 = styled.img`
// 	width: 32px;
// 	height: 32px;
// 	object-fit: cover;
// 	position: absolute;
// 	left: 20px;
// 	top: 20px;
// `;

// const WidgetMSizeBigCircleChart = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 18px;
// 	border-radius: 10px;
// 	box-sizing: border-box;
// 	position: absolute;
// 	left: 60px;
// 	top: calc((calc((50% + 288px)) - 44px));
// 	width: 220px;
// 	height: 88px;
// `;

// const Chart_0002 = styled.div`
// 	width: 88px;
// 	height: 88px;
// 	position: relative;
// `;

// const Percent = styled.span`
// 	color: rgb(23, 23, 37);
// 	text-overflow: ellipsis;
// 	font-size: 24px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 300;
// 	text-align: center;
// 	min-height: 37px;
// 	position: absolute;
// 	left: 13px;
// 	top: calc((calc((50% + 1px)) - 19px));
// 	right: 13px;
// 	height: 37px;
// `;

// const Background_0004 = styled.div`
// 	width: 88px;
// 	height: 88px;
// 	border-radius: 88px / 88px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// `;

// const Progress = styled.img`
// 	width: 88px;
// 	height: 88px;
// 	object-fit: contain;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// `;

// const Info_0004 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: column;
// 	align-items: flex-start;
// 	flex: none;
// 	gap: 1px;
// 	box-sizing: border-box;
// `;

// const Amount_0003 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 20px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 400;
// 	line-height: 32px;
// 	text-align: left;
// 	width: 70px;
// 	min-height: 30px;
// `;

// const Detail = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 16px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 300;
// 	line-height: 24px;
// 	text-align: left;
// 	width: 108px;
// 	min-height: 25px;
// `;

// const WidgetMSizeBigCircleChart_0001 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 18px;
// 	border-radius: 10px;
// 	box-sizing: border-box;
// 	position: absolute;
// 	left: 330px;
// 	top: calc((calc((50% + 288px)) - 44px));
// 	width: 220px;
// 	height: 88px;
// `;

// const HexMap = styled.div`
// 	width: 1341px;
// 	height: 756px;
// 	position: absolute;
// 	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
// 	top: calc((calc((50% + -53px)) - 378px));
// 	right: 137px;
// `;

// const MapPinPinWithName = styled.div`
// 	width: 180px;
// 	height: 72px;
// 	position: absolute;
// 	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
// 	top: calc((calc((50% + -214px)) - 36px));
// 	right: 1147px;
// `;

// const Tooltip = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 12px;
// 	border-radius: 16px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 6px 10px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	width: 184px;
// 	height: 60px;
// `;

// const Indicator = styled.img`
// 	width: 40px;
// 	height: 40px;
// 	object-fit: cover;
// `;

// const Title_0004 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 16px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 300;
// 	line-height: 20px;
// 	text-align: left;
// `;

// const Amount_0005 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 20px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 600;
// 	line-height: 28px;
// 	text-align: left;
// `;

// const Arrow = styled.svg`
// 	width: 26px;
// 	height: 18px;
// 	position: absolute;
// 	left: calc((calc((50% + 26px)) - 13px));
// 	bottom: -18px;
// 	transform: rotate(-180deg);
// 	transform-origin: top left;
// `;

// const MapPinPinWithName_0001 = styled.div`
// 	width: 180px;
// 	height: 72px;
// 	position: absolute;
// 	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
// 	top: calc((calc((50% + 33px)) - 36px));
// 	right: 1024px;
// `;

// const Tooltip_0001 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 12px;
// 	border-radius: 16px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 6px 10px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	width: 177px;
// 	height: 60px;
// `;

// const MapPinPinWithName_0002 = styled.div`
// 	width: 180px;
// 	height: 72px;
// 	position: absolute;
// 	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
// 	top: calc((calc((50% + -296px)) - 36px));
// 	right: 692px;
// `;

// const Tooltip_0002 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 12px;
// 	border-radius: 16px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 6px 10px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	width: 174px;
// 	height: 60px;
// `;

// const MapPinPinWithName_0003 = styled.div`
// 	width: 180px;
// 	height: 72px;
// 	position: absolute;
// 	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
// 	top: calc((calc((50% + -80px)) - 36px));
// 	right: 605px;
// `;

// const Tooltip_0003 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 12px;
// 	border-radius: 16px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 6px 10px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	width: 180px;
// 	height: 60px;
// `;

// const MapPinPinWithName_0004 = styled.div`
// 	width: 180px;
// 	height: 72px;
// 	position: absolute;
// 	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
// 	top: calc((calc((50% + -148px)) - 36px));
// 	right: 224px;
// `;

// const MapPinPinWithName_0005 = styled.div`
// 	width: 180px;
// 	height: 72px;
// 	position: absolute;
// 	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
// 	top: calc((calc((50% + 152px)) - 36px));
// 	right: 113px;
// `;

// const Tooltip_0005 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	gap: 12px;
// 	border-radius: 16px;
// 	background-color: white;
// 	box-sizing: border-box;
// 	padding: 6px 10px;
// 	position: absolute;
// 	left: 0px;
// 	top: 0px;
// 	width: 173px;
// 	height: 60px;
// `;

// const Description = styled.span`
// 	color: rgb(90, 90, 137);
// 	text-overflow: ellipsis;
// 	font-size: 10px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 700;
// 	letter-spacing: 2px;
// 	line-height: 16px;
// 	text-align: left;
// 	text-transform: uppercase;
// 	position: absolute;
// 	left: 67px;
// 	top: calc((calc((50% + 0px)) - 8px));
// `;

// const Amount_0011 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 72px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 500;
// 	letter-spacing: -2px;
// 	line-height: 118px;
// 	text-align: left;
// 	position: absolute;
// 	left: 60px;
// 	top: 201px;
// `;

// const Title_0010 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: flex-end;
// 	gap: 24px;
// 	box-sizing: border-box;
// 	position: absolute;
// 	left: 60px;
// 	top: 183px;
// 	width: 177px;
// 	height: 32px;
// `;

// const Name = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 20px;
// 	font-family: Poppins, sans-serif;
// 	font-weight: 600;
// 	line-height: 32px;
// 	text-align: left;
// `;

// const Detail_0002 = styled.div`
// 	display: flex;
// 	justify-content: flex-start;
// 	flex-direction: row;
// 	align-items: center;
// 	flex: none;
// 	gap: 1px;
// 	box-sizing: border-box;
// `;

// const Detail_0003 = styled.span`
// 	color: rgb(56, 56, 116);
// 	text-overflow: ellipsis;
// 	font-size: 10px;
// 	font-family: Roboto, sans-serif;
// 	font-weight: 700;
// 	letter-spacing: 2px;
// 	line-height: 16px;
// 	text-align: left;
// 	text-transform: uppercase;
// `;

// const Arow = styled.img`
// 	width: 24px;
// 	height: 24px;
// 	object-fit: cover;
// `;

const WidgetLSizeGlobalStatistic = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 37px;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	border-radius: 20px;
	background-color: white;
	box-sizing: border-box;
	padding: 20px 30px;
	position: absolute;
	left: 442px;
	top: 184px;
	width: 1071px;
	height: 528px;
`;

const Header = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 24px;
	box-sizing: border-box;
`;

const Title_0011 = styled.span`
	color: rgb(23, 23, 37);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	text-align: left;
	width: 457px;
`;

const Legend = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const Shape = styled.div`
	width: 12px;
	height: 12px;
	background-color: rgb(164, 108, 233);
	border-radius: 7px;
`;

const MarketingSales = styled.span`
	color: rgb(68, 68, 79);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 28px;
	text-align: left;
	width: 100px;
`;

const Shape_0001 = styled.div`
	width: 12px;
	height: 12px;
	background-color: rgb(250, 230, 52);
	border-radius: 7px;
`;

const Shape_0002 = styled.div`
	width: 12px;
	height: 12px;
	background-color: rgb(252, 113, 125);
	border-radius: 7px;
`;

const Shape_0003 = styled.div`
	width: 12px;
	height: 12px;
	background-color: rgb(105, 93, 251);
	border-radius: 7px;
`;

const Graph_0001 = styled.div`
	width: 1011px;
	height: 423px;
	position: relative;
`;

const Chart_0004 = styled.div`
	width: 1011px;
	height: 423px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const YAxis = styled.div`
	width: 31px;
	height: 379px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const _1K = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	position: absolute;
	left: 9px;
	top: calc((calc((50% + -178px)) - 12px));
	right: 9px;
	opacity: 0.6;
`;

const _0 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	position: absolute;
	left: 18px;
	top: calc((calc((50% + 178px)) - 12px));
	right: 3px;
	opacity: 0.6;
`;

const _200 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 107px)) - 12px));
	right: 1px;
	opacity: 0.6;
`;

const _400 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 36px)) - 12px));
	right: 0px;
	opacity: 0.6;
`;

const _600 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + -36px)) - 12px));
	right: 0px;
	opacity: 0.6;
`;

const _800 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + -107px)) - 12px));
	right: 0px;
	opacity: 0.6;
`;

const XAxis = styled.div`
	width: 961px;
	height: 423px;
	position: absolute;
	left: 50px;
	top: 0px;
`;

const Dec = styled.div`
	overflow: hidden;
	position: absolute;
	left: 931px;
	top: 0px;
	right: -0px;
	bottom: 0px;
`;

const Name_0001 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: -1px;
	top: calc((calc((50% + 197px)) - 12px));
	right: -1px;
	opacity: 0.6;
`;

const Shape_0004 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 14px;
	top: -0px;
	right: 15px;
	bottom: 39px;
`;

const Nov = styled.div`
	overflow: hidden;
	position: absolute;
	left: 845px;
	top: 0px;
	right: 86px;
	bottom: 0px;
`;

const Name_0002 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 197px)) - 12px));
	right: -1px;
	opacity: 0.6;
`;

const Oct = styled.div`
	overflow: hidden;
	position: absolute;
	left: 763px;
	top: 0px;
	right: 172px;
	bottom: 0px;
`;

const Name_0003 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: -2px;
	top: calc((calc((50% + 197px)) - 12px));
	right: -1px;
	opacity: 0.6;
`;

const Shape_0006 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 11px;
	top: -0px;
	right: 14px;
	bottom: 39px;
`;

const Sep = styled.div`
	overflow: hidden;
	position: absolute;
	left: 678px;
	top: 0px;
	right: 254px;
	bottom: 0px;
`;

const Shape_0007 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 13px;
	top: -0px;
	right: 15px;
	bottom: 39px;
`;

const Aug = styled.div`
	overflow: hidden;
	position: absolute;
	left: 592px;
	top: 0px;
	right: 339px;
	bottom: 0px;
`;

const Name_0005 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: -1px;
	top: calc((calc((50% + 197px)) - 12px));
	right: -2px;
	opacity: 0.6;
`;

const Jul = styled.div`
	overflow: hidden;
	position: absolute;
	left: 512px;
	top: 0px;
	right: 425px;
	bottom: 0px;
`;

const Name_0006 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: 1px;
	top: calc((calc((50% + 197px)) - 12px));
	right: 0px;
	opacity: 0.6;
`;

const Shape_0009 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 10px;
	top: -0px;
	right: 13px;
	bottom: 39px;
`;

const Jun = styled.div`
	overflow: hidden;
	position: absolute;
	left: 427px;
	top: 0px;
	right: 505px;
	bottom: 0px;
`;

const Name_0007 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: -1px;
	top: calc((calc((50% + 197px)) - 12px));
	right: -0px;
	opacity: 0.6;
`;

const Shape_0010 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 15px;
	top: -0px;
	right: 13px;
	bottom: 39px;
`;

const May = styled.div`
	overflow: hidden;
	position: absolute;
	left: 339px;
	top: 0px;
	right: 590px;
	bottom: 0px;
`;

const Shape_0011 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 17px;
	top: -0px;
	right: 14px;
	bottom: 39px;
`;

const Apr = styled.div`
	overflow: hidden;
	position: absolute;
	left: 255px;
	top: 0px;
	right: 678px;
	bottom: 0px;
`;

const Name_0009 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: -1px;
	top: calc((calc((50% + 197px)) - 12px));
	right: 1px;
	opacity: 0.6;
`;

const Shape_0012 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 15px;
	top: -0px;
	right: 11px;
	bottom: 39px;
`;

const Mar = styled.div`
	overflow: hidden;
	position: absolute;
	left: 169px;
	top: 0px;
	right: 761px;
	bottom: 0px;
`;

const Name_0010 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: center;
	position: absolute;
	left: -0px;
	top: calc((calc((50% + 197px)) - 12px));
	right: -1px;
	opacity: 0.6;
`;

const Shape_0013 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 15px;
	top: -0px;
	right: 14px;
	bottom: 39px;
`;

const Feb = styled.div`
	overflow: hidden;
	position: absolute;
	left: 85px;
	top: 0px;
	right: 847px;
	bottom: 0px;
`;

const Shape_0014 = styled.svg`
	width: 1px;
	height: 384px;
	position: absolute;
	left: 16px;
	top: -0px;
	right: 11px;
	bottom: 39px;
`;

const Jan = styled.div`
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 932px;
	bottom: 0px;
`;

const Data = styled.div`
	width: 893px;
	height: 286px;
	position: absolute;
	left: 97px;
	top: 24px;
`;

const Bubble = styled.div`
	width: 16px;
	height: 16px;
	background-color: rgb(147, 82, 229);
	border-radius: 16px / 16px;
	position: absolute;
	left: 827px;
	top: 198px;
`;

const Bubble_0001 = styled.div`
	width: 25px;
	height: 25px;
	background-color: rgb(147, 82, 229);
	border-radius: 25px / 25px;
	position: absolute;
	left: 446px;
	top: 250px;
`;

const Bubble_0002 = styled.div`
	width: 16px;
	height: 16px;
	background-color: rgb(147, 82, 229);
	border-radius: 16px / 16px;
	position: absolute;
	left: 599px;
	top: 119px;
`;

const Bubble_0003 = styled.div`
	width: 16px;
	height: 16px;
	background-color: rgb(147, 82, 229);
	border-radius: 16px / 16px;
	position: absolute;
	left: 77px;
	top: 161px;
`;

const Bubble_0004 = styled.div`
	width: 77px;
	height: 77px;
	box-shadow: 0px 109px 80px  rgba(226, 13, 148, 0.13),0px 46px 33px  rgba(226, 13, 148, 0.09),0px 24px 18px  rgba(226, 13, 148, 0.08),0px 14px 10px  rgba(226, 13, 148, 0.06),0px 7px 5px  rgba(226, 13, 148, 0.05),0px 3px 2px  rgba(226, 13, 148, 0.04);
	background-color: rgb(255, 115, 125);
	border-radius: 77px / 77px;
	position: absolute;
	left: 740px;
	top: 185px;
`;

const Bubble_0005 = styled.div`
	width: 94px;
	height: 94px;
	background-color: rgb(249, 224, 1);
	border-radius: 94px / 94px;
	position: absolute;
	left: 215px;
	top: 192px;
	opacity: 0.8;
`;

const Bubble_0006 = styled.div`
	width: 68px;
	height: 68px;
	box-shadow: 0px 109px 80px  rgba(132, 13, 226, 0.14),0px 46px 33px  rgba(132, 13, 226, 0.1),0px 24px 18px  rgba(132, 13, 226, 0.08),0px 14px 10px  rgba(132, 13, 226, 0.07),0px 7px 5px  rgba(132, 13, 226, 0.06),0px 3px 2px  rgba(132, 13, 226, 0.04);
	background-color: rgba(105, 93, 251, 0.8);
	border-radius: 68px / 68px;
	position: absolute;
	left: 703px;
	top: 94px;
`;

const Bubble_0007 = styled.div`
	width: 25px;
	height: 25px;
	background-color: rgb(105, 93, 251);
	border-radius: 25px / 25px;
	position: absolute;
	left: 561px;
	top: 169px;
`;

const Bubble_0008 = styled.div`
	width: 44px;
	height: 44px;
	background-color: rgb(147, 82, 229);
	border-radius: 44px / 44px;
	position: absolute;
	left: 848px;
	top: 219px;
`;

const Bubble_0009 = styled.div`
	width: 44px;
	height: 44px;
	box-shadow: 0px 109px 80px  rgba(132, 13, 226, 0.14),0px 46px 33px  rgba(132, 13, 226, 0.1),0px 24px 18px  rgba(132, 13, 226, 0.08),0px 14px 10px  rgba(132, 13, 226, 0.07),0px 7px 5px  rgba(132, 13, 226, 0.06),0px 3px 2px  rgba(132, 13, 226, 0.04);
	background-color: rgba(147, 82, 229, 0.8);
	border-radius: 44px / 44px;
	position: absolute;
	left: 0px;
	top: 214px;
`;

const Bubble_0010 = styled.div`
	width: 34px;
	height: 34px;
	background-color: rgb(250, 230, 52);
	border-radius: 34px / 34px;
	position: absolute;
	left: 102px;
	top: 92px;
`;

const Bubble_0011 = styled.div`
	width: 147px;
	height: 146px;
	position: absolute;
	left: 119px;
	top: 109px;
`;

const Bubble_0012 = styled.div`
	width: 147px;
	height: 146px;
	box-shadow: 0px 100px 80px  rgba(255, 43, 43, 0.15),0px 46px 37px  rgba(255, 43, 43, 0.11),0px 26px 21px  rgba(255, 43, 43, 0.09),0px 16px 13px  rgba(255, 43, 43, 0.08),0px 10px 8px  rgba(255, 43, 43, 0.07),0px 5px 4px  rgba(255, 43, 43, 0.06),0px 2px 2px  rgba(255, 43, 43, 0.04);
	background-color: rgb(255, 80, 93);
	border-radius: 147px / 146px;
	position: absolute;
	left: 0px;
	top: 0px;
	opacity: 0.8;
`;

const Value_0006 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	text-align: center;
	min-height: 28px;
	position: absolute;
	left: 40px;
	top: calc((calc((50% + -0px)) - 14px));
	right: 39px;
	height: 28px;
`;

const Bubble_0013 = styled.div`
	width: 130px;
	height: 129px;
	position: absolute;
	left: 626px;
	top: 133px;
`;

const Bubble_0014 = styled.div`
	width: 130px;
	height: 129px;
	background-color: rgb(250, 230, 52);
	border-radius: 130px / 129px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Value_0007 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	text-align: center;
	min-height: 28px;
	position: absolute;
	left: 31px;
	top: calc((calc((50% + 0px)) - 14px));
	right: 31px;
	height: 28px;
`;

const Bubble_0015 = styled.div`
	width: 248px;
	height: 247px;
	position: absolute;
	left: 217px;
	top: 0px;
`;

const Bubble_0016 = styled.div`
	width: 248px;
	height: 247px;
	box-shadow: 0px 109px 80px  rgba(132, 13, 226, 0.14),0px 46px 33px  rgba(132, 13, 226, 0.1),0px 24px 18px  rgba(132, 13, 226, 0.08),0px 14px 10px  rgba(132, 13, 226, 0.07),0px 7px 5px  rgba(132, 13, 226, 0.06),0px 3px 2px  rgba(132, 13, 226, 0.04);
	background-color: rgb(105, 93, 251);
	border-radius: 248px / 247px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Value_0008 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	text-align: center;
	min-height: 28px;
	position: absolute;
	left: 90px;
	top: calc((calc((50% + -4px)) - 14px));
	right: 91px;
	height: 28px;
`;

const Text = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: center;
	min-height: 18px;
	position: absolute;
	left: 98px;
	top: calc((calc((50% + 18px)) - 9px));
	right: 98px;
	height: 18px;
`;

const Name_0013 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: Archivo, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 161px;
	position: absolute;
	left: 91px;
	top: calc((calc((50% + -510px)) - 11px));
`;

const WstfLogo1 = styled.div`
	width: 40px;
	height: 40px;
	overflow: hidden;
	position: absolute;
	left: 42px;
	top: 10px;
`;

const Group = styled.div`
	width: 39px;
	height: 39px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 0px;
	top: 0px;
`;

const Vector = styled.img`
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;
